### ISSUE TITLE
3がつく数のリングの色

### ISSUE THREAD

**Issue by rikakobayashi** [kashiwa-mochi/count_adv-#1]
カウンターの値が3がつく数の場合にリングの色が変化していないので修正お願いします！

**Comment by kashiwa-mochi** [comment]
修正しました！確認お願いしますm(_ _)m

**Comment by kaim18** [comment]
今の条件式の書き方だと、実装の要件を満たすためには、10, 100, 1000, 10000と無限にif文を増やしていく必要があります。
以下のURLなどを参考に条件を満たす式に変更してみてください
https://docs.ruby-lang.org/en/3.0.0/Integer.html#method-i-inspect
https://docs.ruby-lang.org/ja/latest/method/String/i/include=3f.html

**Comment by kashiwa-mochi** [comment]
3のある時のカラー、新たな色の組み合わせ追加しました。チェックお願いします！

**Comment by kaim18** [comment]
今の実装だと。

5の倍数かつ3がつく数字(e.g. 35) の時にリングの色が変わらないので  
条件式を整理してもう少しだけ考えてみてほしいです！

**Comment by kashiwa-mochi** [comment]
ごめんなさい、気づかなくて少し遅れてしまいました。
条件式、直したのでチェックお願いします

**Comment by rikakobayashi** [comment]
if文の条件式は上から評価していくので、15の倍数の数が3の倍数の条件に当てはまってしまいます。
またCSSは同じプロパティがあった時に、後ろに書かれた方で上書きされるので、文字色がうまく反映できていません。
確認して直してみてください！

**Comment by kashiwa-mochi** [comment]
slackのほうで連絡した通り更新してあるので確認お願いします

**Comment by rikakobayashi** [comment]
確認しました。0の時が通常時と同じ色になっていないのですが、そこだけなのでOKとします〜
